
let config =
{
  selectLayout: [//应用布局
    { name: "header", style: { "background-color": "rgb(57,162,237);" }, color: "rgb(57,162,237)", visible: true },
    { name: "aside", style: { "background-color": "rgb(57,162,237);" }, color: "rgb(57,162,237)",visible: false, width: "60px", },
    { name: "main", style: { "background-color": "rgb(255,255,255);" }, color: "rgb(255,255,255)", visible: true },
    { name: "footer", style: { "background-color": "rgb(57,162,237);" }, color: "rgb(57,162,237)", visible: false },
    { name: "", style: {"background-color": "rgb(255,255,255);" }, color: "rgb(255,255,255)", visible: false},
    { name: "tool", style: {'background-color': '#fff','box-shadow': '0 1px 2px rgba(0, 0, 0, 0.3)', border: 'none'}, toolIconColor: 'rgba(0,0,0,1)', visible: true}],
  widgets: [//地图微件
    {
      id: 0, widgets: [
        { id: 0, name: "scalebar", visible: false, position: "bottom-left", alt: '比例尺' },
        { id: 1, name: "coordinateConversion", visible: false, position: "bottom-right", alt: '坐标' },
        { id: 2, name: "compass", visible: false, position: "top-right", alt: '指北针' },
        { id: 3, name: "fullscreen", visible: false, position: "top-right", alt: '全屏' },
        { id: 4, name: "home", visible: false, position: "top-left", alt: '回到初始地图' },
        { id: 5, name: "print", visible: false, position: "top-left", alt: '打印' },
        { id: 6, name: "legend", visible: false, position: "top-left", alt: '图例' },]
    },
    // {
    //   id: 1, widgets: [//固定在悬浮card中的组件
    //     { id: 0, name: "resource_catalog", visible: false, position: "absolute", alt: '资源目录' },
    //     { id: 1, name: "layer_list", visible: true, position: "absolute", alt: '图层列表' },
    //     { id: 2, name: "export_map", visible: false, position: "absolute", alt: '成果输出' },
    //     { id: 3, name: "switch_basemap", visible: false, position: "absolute", alt: '切换底图' },
    //     { id: 4, name: "spatial_query", visible: false, position: "absolute", alt: '空间查询' },
    //     { id: 5, name: "feature_analyse",visible: false, position: "absolute", alt: '要素分析'},]
    // },
    {
      id: 1, widgets: [//固定在悬浮card中的组件
        { id: 0, name: "layer_list", btnid: "layer_list", type: "button", icon: "&#xe66d;", visible: true, position: "absolute", alt: '图层列表' },
        { id: 1, name: "line_measure", btnid: "distanceButton", type: "button", icon: "&#xe65b;", visible: false, position: "absolute", alt: '长度测量' },
        { id: 2, name: "area_measure", btnid: "areaButton", type: "button", icon: "&#xe658;", visible: false, position: "absolute", alt: '面积测量' },
        { id: 3, name: "property_search", btnid: "propertyButton", type: "button", icon: "&#xe79a;", visible: false, position: "absolute", alt: '属性查询' },
        { id: 4, name: "spatial_query", btnid: "spatialQueryButton", type:"button", icon: "&#xe65c;", visible: false, position: "absolute", alt: '空间查询'},
        { id: 5, name: "point_search", btnid: "pointButton", type: "button", icon: "&#xed1b;", visible: false, position: "absolute", alt: '单点查询' },
        { id: 6, name: "bookmarks", btnid: "bookmarksButton", type: "button", icon: "&#xe7ae;", visible: false, position: "absolute", alt: '书签' },
        { id: 7, name: "mutiscreen", btnid: "mutiscreenButton", type: "button", icon: "&#xe7b8;", visible: false, position: "absolute", alt: '多屏对比' },
        { id: 8, name: "swipe", btnid: "swipeButton", type: "button", icon: "&#xe664;", visible: false, position: "absolute", alt: '卷帘' },
        { id: 9, name: "intersectAnalyse", btnid: "intersectAnalyseButton", type: "button", icon: "&#xe665;", visible: false, position: "absolute", alt: '叠加分析' },
        { id: 10, name: "clear_map", btnid: "clearButton", type: "button", icon: "&#xe663;", visible: false, position: "absolute", alt: '清除' },
        { id: 11, name: "edit", btnid: "editButton", type: "button", icon: "&#xe603;", visible: false, position: "absolute", alt: '编辑'},
        { id: 12, name: "sketch", btnid: "sketchButton", type: "dropdown", icon: "&#xe603;", visible: false, position: "absolute", alt: '标绘'},
        { id: 13, name: "export_map", btnid: "export_map", type:"button", icon: "&#xe65d;", visible: false, position: "absolute", alt: '成果输出'},
        { id: 14, name: "switch_basemap", btnid: 'switch_basemap', type:"button", icon: "&#xe64e;", visible: false, position: "absolute", alt: '切换底图'},
        { id: 15, name: "feature_analyse", btnid: 'feature_analyse', type:"button", icon: "&#xe64b;", visible: false, position: "absolute", alt: '要素分析'},
        { id: 16, name: "resource_catalog", btnid: 'resource_catalog', type:"button", icon: "&#xe657;", visible: false, position: "absolute", alt: '资源编目'}]
    },
  ],
  btnControlWidgets: [//通过按钮控制，在地图上展示的工具
  ],
  appTitle: [{ name: "未命名应用" }, { name: "" }, { name: "我的地图应用" }],//应用标题，副标题，描述
  mapInfomation: {//地图图层信息
    "spatialReference": 4528, "center":
      { "spatialReference": { "latestWkid": 4528, "wkid": 4528, "x": 40617930.15481129, "y": 4602140.753924502},},
    "zoom": 12,
    "baseMapLayers": { "layers": { "children": [{ "title": "行政区", "url": "http://192.168.48.12:6080/arcgis/rest/services/XZQ/XZQH_YXXZQ_2020_4528/MapServer", "type": "tile", "opacity": 1 }] } },
    "mapLayers": {
      "layers": {
        "children": [{ "title": "资源目录图层组", "type": "group", "opacity": 1, "children": { "children": [{ "title": "STBHZYX", "url": "http://192.168.48.12:6080/arcgis/rest/services/XZL/TDLYXZ_DLTB_2009_4528/MapServer", "type": "tile", "opacity": 1 }] } },
        { "title": "自定义图层组", "type": "group", "opacity": 1, "children": { "children": [] } }]
      }
    },
    "groundLayers": { "layers": { "children": [] } }
  },
//   baseMapGroup: [{
//     ASSA: "MapServer",
//     COLLECT: null,
//     COVERAGEAREA: null,
//     DOCUMENTINFOTITLE: "CZJSSYX",
//     FULLEXTENTLATESTWKID: "4529",
//     FULLEXTENTWKID: "4529",
//     FULLEXTENTWKT: null,
//     FULLEXTENTXMAX: "41557562.5976",
//     FULLEXTENTXMIN: "41465446.440799996",
//     FULLEXTENTYMAX: "4587810.720600001",
//     FULLEXTENTYMIN: "4508520.864099999",
//     ID: 4979,
//     IMAGE: "",
//     INITIALEXTENTLATESTWKID: "4529",
//     INITIALEXTENTWKID: "4529",
//     INITIALEXTENTWKT: null,
//     INITIALEXTENTXMAX: "41570475.28881212",
//     INITIALEXTENTXMIN: "41452533.74958787",
//     INITIALEXTENTYMAX: "4591775.213425",
//     INITIALEXTENTYMIN: "4532944.516899838",
//     LATESTWKID: "4529",
//     LAYERS: null,
//     NAME: null,
//     ORDER: null,
//     PAGENUM: null,
//     PAGESIZE: null,
//     REGION: "210727",
//     SERVICEADDRESS: "http://192.168.50.13:6080/arcgis/rest/services/FXPJ/CZJSSYX/MapServer",
//     SERVICEDESCRIPTION: null,
//     SINGLEFUSEDMAPCACHE: "false",
//     SMID: "41eb2bf4752ef753728677778d723d88",
//     SPATIALREFERENCE: "CGCS2000_3_Degree_GK_Zone_41",
//     SRID: 3919,
//     SUMMARY: null,
//     SUPPORTEDIMAGEFORMATTYPES: "PNG32,PNG24,PNG,JPG,DIB,TIFF,EMF,PS,PDF,GIF,SVG,SVGZ,BMP",
//     TAGS: null,
//     TEXT: "CZJSSYX",
//     TITLE: "CZJSSYX",
//     TOTAL: null,
//     TYPE: "MapImageLayer",
//     UNITS: "esriMeters",
//     WKID: 4529,
//     WKT: null,
//     selectedCheck: false,
//   },
//   {
//     ASSA: "MapServer",
//     COLLECT: null,
//     COVERAGEAREA: "辽阳县",
//     DOCUMENTINFOTITLE: "2016年行政区划图",
//     FULLEXTENTLATESTWKID: "4490",
//     FULLEXTENTWKID: "4490",
//     FULLEXTENTWKT: null,
//     FULLEXTENTXMAX: "123.683723504",
//     FULLEXTENTXMIN: "122.585511215",
//     FULLEXTENTYMAX: "41.42302653899998",
//     FULLEXTENTYMIN: "40.70580123299999",
//     ID: 5067,
//     IMAGE:"",
//     INITIALEXTENTLATESTWKID: "4490",
//     INITIALEXTENTWKID: "4490",
//     INITIALEXTENTWKT: null,
//     INITIALEXTENTXMAX: "123.73863411845",
//     INITIALEXTENTXMIN: "122.53060060055",
//     INITIALEXTENTYMAX: "41.45888780429998",
//     INITIALEXTENTYMIN: "40.66993996769999",
//     LATESTWKID: "4490",
//     LAYERS: null,
//     NAME: null,
//     ORDER: null,
//     PAGENUM: null,
//     PAGESIZE: null,
//     REGION: "210727",
//     SERVICEADDRESS: "http://172.16.171.242:6080/arcgis/rest/services/XZQH/JCDL_XZQH_2016/MapServer",
//     SERVICEDESCRIPTION: "//比例尺：1:10000↵//服务发布时间：2019-05-17",
//     SINGLEFUSEDMAPCACHE: "true",
//     SMID: "be8c220e7a7c2a6abefa032a1f84cfec",
//     SPATIALREFERENCE: "GCS_China_Geodetic_Coordinate_System_2000",
//     SRID: 129,
//     SUMMARY: "2016年辽阳县行政区划图",
//     SUPPORTEDIMAGEFORMATTYPES: "PNG32,PNG24,PNG,JPG,DIB,TIFF,EMF,PS,PDF,GIF,SVG,SVGZ,BMP",
//     TAGS: "现状类;遥感测绘;基础地理;2016;辽阳县;全覆盖;",
//     TEXT: "JCDL_XZQH_2016",
//     TITLE: "2016年行政区划图",
//     TOTAL: null,
//     TYPE: "TileLayer",
//     UNITS: "esriDecimalDegrees",
//     WKID: 4490,
//     WKT: null,
//     selectedCheck: false},],
};

config=window.vpgis && window.vpgis.config?window.vpgis.config:config

/*地图应用参数设置*/
export default config// 输出
